# -*- coding: utf-8 -*-
"""PDL 1-predict-class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFjjd8NploGl8kaXg3YjIcitq9jnsQRQ

<table class="tfo-notebook-buttons" align="center">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/practicaldl/Practical-Deep-Learning-Book/blob/master/code/chapter-2/1-predict-class.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/practicaldl/Practical-Deep-Learning-Book/blob/master/code/chapter-2/1-predict-class.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

This code is part of [Chapter 2 - What’s in the Picture: Image Classification with Keras](https://learning.oreilly.com/library/view/practical-deep-learning/9781492034858/ch02.html).
"""

try:
  import google.colab
  IS_COLAB_ENV = True
except:
  IS_COLAB_ENV = False
IS_COLAB_ENV

if IS_COLAB_ENV:
    !pip install tensorflow==2.8.0

"""# Predict Category of an Image

The image classification task simply answers the question “Does the image contain X” where X can be a cat, dog or any other category/class of objects. In this file, we see the code for predicting categories for an image.

We start off by importing all the necessary modules from Keras and Python packages. Numpy here gives us the ability to transform matrices, while Matplotlib is graph plotting library that also allows us to display images.
"""

import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

"""Once we have imported our libraries, we will load and display our test image in a 224x224 resolution."""

IMG_PATH_CAT = '../../sample-images/cat.jpg'
IMG_PATH_DOG = '../../sample-images/dog.jpg'
IMG_PATH_LAPTOP = '../../sample-images/laptop.jpg'
IMG_PATH_BOOK = '../../sample-images/book.jpg'

if IS_COLAB_ENV:
  !curl https://raw.githubusercontent.com/PracticalDL/Practical-Deep-Learning-Book/master/sample-images/cat.jpg --output cat.jpg
  !curl https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2022/6/16/1/shutterstock_733569046.jpg.rend.hgtvcom.791.527.suffix/1655430860333.jpeg --output dog.jpg
  !curl https://m.media-amazon.com/images/I/41nk9CwuPOL._SX300_SY300_QL70_FMwebp_.jpg
  !curl https://media.newyorker.com/photos/59ee325f1685003c9c28c4ad/master/w_1920,c_limit/Heller-Kirkus-Reviews.jpg --output book.jpg

  IMG_PATH_CAT = 'cat.jpg'
  IMG_PATH_DOG = 'dog.jpg'
  IMG_PATH_LAPTOP = 'laptop.jpg'
  IMG_PATH_BOOK = 'book.jpg'

#Display cat
img = image.load_img(IMG_PATH_CAT, target_size=(224, 224))
plt.imshow(img)
plt.show()

#Display dog
img = image.load_img(IMG_PATH_DOG, target_size=(224, 224))
plt.imshow(img)
plt.show()

#Display laptop
img = image.load_img(IMG_PATH_BOOK, target_size=(224, 224))
plt.imshow(img)
plt.show()

model = tf.keras.applications.resnet50.ResNet50()

"""Our model has previously been trained only to accept a batch of images. `expand_dims` adds an extra dimension to the array, thereby creating an array of arrays (or a batch of one image)."""

def predict(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    model = tf.keras.applications.resnet50.ResNet50()
    img_array = image.img_to_array(img)
    img_batch = np.expand_dims(img_array, axis=0)
    img_preprocessed = preprocess_input(img_batch)
    prediction = model.predict(img_preprocessed)
    print(decode_predictions(prediction, top=3)[0])

cat_pred = predict(IMG_PATH_CAT)
dog_pred = predict(IMG_PATH_DOG)
book_pred = predict(IMG_PATH_BOOK)