# Generated by Django 4.2.4 on 2023-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintant_name', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('who', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('dept', models.CharField(choices=[('cse', 'CSE'), ('csm', 'CSM'), ('cic', 'CIC'), ('cso', 'CSO'), ('it', 'IT'), ('mech', 'MECH'), ('civil', 'CIVIL'), ('aiml', 'AIML'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('AIDS', 'AIDS')], max_length=10)),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('g', models.CharField(choices=[('academic', 'Academic'), ('non-academic', 'Non-Academic'), ('discrimination', 'Discrimination')], max_length=20)),
                ('Grevience_column', models.TextField()),
            ],
        ),
    ]
