# Generated by Django 4.2.4 on 2023-08-31 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('affiliation_university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('complainant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('complainant_choice', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('student', 'Student'), ('prof', 'Professor'), ('assoc_prof', 'Associate Professor'), ('asst_prof', 'Assistant Professor')], default='student', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceMember',
            fields=[
                ('grievance_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('departments', models.ManyToManyField(to='GrievancesRegistration.department')),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('grievance_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_occurrence', models.DateTimeField()),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], max_length=10)),
                ('grievance_category', models.CharField(max_length=100)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievancesRegistration.complainant')),
            ],
        ),
        migrations.AddField(
            model_name='complainant',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievancesRegistration.department'),
        ),
    ]
