# Generated by Django 5.0 on 2024-01-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='my_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
