library(palmerpenguins)
library(stats)
library(dplyr)
library(PerformanceAnalytics)
library(DT)
library(tidyr)
library(caret)
library(e1071)
library(kableExtra)
library(caTools)
library(MASS)
library(devtools)
library(ggord)
library(klaR)
library(naivebayes)

penguin_data <- glimpse(penguins)
penguin_data