# Generated by Django 5.0 on 2023-12-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
