Mywdg:

<Mywdg>:
    text: demo.ti.text
    Demo:
        id:demo
    Button:
        id:my_button
        text:"Submit"
        on_press:root.submit(demo.label)

<Demo>:
    label:my_label
    ti:my_ti
    Label:
        id:my_label
        text:"Yo"
    TextInput:
        id:my_ti
        #on_text:root.on_text(self)
    Label:
        text:"HELLO"
    Label:
        text:"HI"
        border_color:0,0,1,1
